# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				giant = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				salmon = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				ender_dragon = true
				evoker = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				enderman = true
				dragon_fireball = true
				chicken = true
				donkey = true
				evoker_fangs = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				cat = true
				zombie = true
				ghast = true
				sheep = true
				player = true
				eye_of_ender = true
				villager = true
				fishing_bobber = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				strider = true
				falling_block = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

